default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:
  # socket: /var/lib/mysql/mysql.sock
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: tsubaken_development
test:
  <<: *default
  database: tsubaken_test

production:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: 3306
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  database: tsubaken_production
